function result = analyzeRepeatedCondition( ...
        runDirs, outputDir, processedDir, initialImagePath, cfg)
%ANALYZEREPEATEDCONDITION Analyze repeated captures of one DUT condition.

arguments
    runDirs (:, 1) string
    outputDir (1, 1) string
    processedDir (1, 1) string
    initialImagePath (1, 1) string {mustBeFile}
    cfg (1, 1) struct
end

validateConfig(cfg);
if isempty(runDirs)
    error("dut:NoRepeatedConditionRuns", ...
        "At least one repeated-condition run directory is required.");
end

runCount = numel(runDirs);
frequencyPointCount = floor(cfg.pointCount/2) + 1;
perRunOutputPsdV2PerHz = zeros(frequencyPointCount, runCount);
frequencyHz = zeros(frequencyPointCount, 1);
inputPaths = strings(runCount, 1);
runRows = repmat(emptyRunRow(), runCount, 1);

for runIndex = 1:runCount
    inputPaths(runIndex) = resolveWaveformPath(runDirs(runIndex));
    [waveformV, sampleRateHz, declaredSampleCount] = readWaveform( ...
        inputPaths(runIndex), cfg.pointCount, cfg.sampleRateHz);
    [outputPsdV2PerHz, runFrequencyHz] = noiseSpectrum( ...
        waveformV, sampleRateHz, cfg.pointCount, false);
    if runIndex == 1
        frequencyHz = runFrequencyHz;
    elseif ~isequal(frequencyHz, runFrequencyHz)
        error("dut:FrequencyAxisMismatch", ...
            "Repeated-condition runs produced inconsistent frequencies.");
    end
    perRunOutputPsdV2PerHz(:, runIndex) = outputPsdV2PerHz;
    runRows(runIndex) = makeRunRow( ...
        runIndex, inputPaths(runIndex), declaredSampleCount, ...
        sampleRateHz, waveformV, runFrequencyHz, ...
        outputPsdV2PerHz, cfg.gain);
end

averageOutputPsdV2PerHz = mean(perRunOutputPsdV2PerHz, 2);
averageInputPsdV2PerHz = averageOutputPsdV2PerHz/cfg.gain^2;
averageInputAsdVrtHz = sqrt(max(averageInputPsdV2PerHz, 0));
runSummary = struct2table(runRows);
conditionSummary = makeConditionSummary( ...
    frequencyHz, averageInputAsdVrtHz, runSummary, runCount, cfg);

paths = buildPaths(outputDir, processedDir);
if ~isfolder(outputDir)
    mkdir(outputDir);
end
if ~isfolder(processedDir)
    mkdir(processedDir);
end

fullSpectrum = table( ...
    frequencyHz, averageInputAsdVrtHz*1e9, ...
    VariableNames=["Frequency_Hz", ...
    "Average_Input_ASD_nV_per_sqrtHz"]);
writetable(fullSpectrum, paths.fullSpectrumCsv);
writetable(runSummary, paths.runSummaryCsv);
writetable(conditionSummary, paths.conditionSummaryCsv);
save(paths.fullAnalysisMat, ...
    "frequencyHz", "averageInputPsdV2PerHz", ...
    "averageInputAsdVrtHz", "averageOutputPsdV2PerHz", ...
    "perRunOutputPsdV2PerHz", "inputPaths", "runSummary", ...
    "conditionSummary", "runCount", "cfg", "-v7.3");

plotData = reduceForPlot( ...
    frequencyHz, averageInputPsdV2PerHz, ...
    cfg.plotFrequencyLimitsHz, cfg.plotBinCount);
processedSpectrum = table( ...
    plotData.frequencyHz, plotData.inputAsdVrtHz*1e9, ...
    VariableNames=["Frequency_Hz", ...
    "Average_Input_ASD_nV_per_sqrtHz"]);
processedRunSummary = runSummary;
processedRunSummary.SourcePath(:) = ...
    "[raw waveform omitted; see data/raw/README.md]";
writetable(processedSpectrum, paths.processedSpectrumCsv);
writetable(processedRunSummary, paths.processedRunSummaryCsv);
writetable(conditionSummary, paths.processedConditionSummaryCsv);
plotFrequencyHz = plotData.frequencyHz;
plotInputPsdV2PerHz = plotData.inputPsdV2PerHz;
plotInputAsdVrtHz = plotData.inputAsdVrtHz;
save(paths.processedPlotDataMat, ...
    "plotFrequencyHz", "plotInputPsdV2PerHz", ...
    "plotInputAsdVrtHz", "processedRunSummary", ...
    "conditionSummary", "runCount", "cfg");

sameFormatFigure = plotSameFormat( ...
    frequencyHz, averageInputAsdVrtHz, cfg);
sameFormatCleanup = onCleanup(@() close(sameFormatFigure));
savefig(sameFormatFigure, paths.sameFormatFig);
exportPixelSizePng(sameFormatFigure, paths.sameFormatPng, [1515, 1293]);

comparisonFigure = plotScreenshotComparison( ...
    initialImagePath, paths.sameFormatPng);
comparisonCleanup = onCleanup(@() close(comparisonFigure));
savefig(comparisonFigure, paths.comparisonFig);
exportPixelSizePng(comparisonFigure, paths.comparisonPng, [3000, 1320]);

result = struct;
result.frequencyHz = frequencyHz;
result.averageInputPsdV2PerHz = averageInputPsdV2PerHz;
result.averageInputAsdVrtHz = averageInputAsdVrtHz;
result.runSummary = runSummary;
result.conditionSummary = conditionSummary;
result.runCount = runCount;
result.outputPaths = paths;
end

function validateConfig(cfg)
requiredFields = [ ...
    "sampleRateHz", "pointCount", "gain", ...
    "plotFrequencyLimitsHz", "plotBinCount", ...
    "referenceNvRtHz", "testLabel", "figureSubtitle"];
missingFields = requiredFields(~isfield(cfg, requiredFields));
if ~isempty(missingFields)
    error("dut:InvalidRepeatedConditionConfig", ...
        "Repeated-condition config is missing: %s", ...
        strjoin(missingFields, ", "));
end
validScalar = @(value) isnumeric(value) && isscalar(value) && ...
    isfinite(value);
validPositiveInteger = @(value) validScalar(value) && ...
    value >= 1 && value == fix(value);
validLimits = isnumeric(cfg.plotFrequencyLimitsHz) && ...
    isequal(size(cfg.plotFrequencyLimitsHz), [1, 2]) && ...
    all(isfinite(cfg.plotFrequencyLimitsHz)) && ...
    all(cfg.plotFrequencyLimitsHz > 0) && ...
    cfg.plotFrequencyLimitsHz(1) < cfg.plotFrequencyLimitsHz(2) && ...
    cfg.plotFrequencyLimitsHz(2) <= cfg.sampleRateHz/2;
validLabels = (isstring(cfg.testLabel) || ischar(cfg.testLabel)) && ...
    strlength(string(cfg.testLabel)) > 0 && ...
    (isstring(cfg.figureSubtitle) || ischar(cfg.figureSubtitle)) && ...
    strlength(string(cfg.figureSubtitle)) > 0;
isValid = validScalar(cfg.sampleRateHz) && cfg.sampleRateHz > 0 && ...
    validPositiveInteger(cfg.pointCount) && cfg.pointCount >= 2 && ...
    validScalar(cfg.gain) && cfg.gain > 0 && ...
    validPositiveInteger(cfg.plotBinCount) && validLimits && ...
    validScalar(cfg.referenceNvRtHz) && cfg.referenceNvRtHz > 0 && ...
    validLabels;
if ~isValid
    error("dut:InvalidRepeatedConditionConfig", ...
        "Repeated-condition configuration contains invalid values.");
end
end

function csvPath = resolveWaveformPath(runDir)
if ~isfolder(runDir)
    error("dut:MissingRunDirectory", ...
        "Repeated-condition run directory does not exist: %s", runDir);
end
files = dir(fullfile(runDir, "*Waveform Data.csv"));
if numel(files) ~= 1
    error("dut:UnexpectedWaveformFileCount", ...
        "Expected exactly one waveform CSV in %s; found %d.", ...
        runDir, numel(files));
end
csvPath = string(fullfile(files(1).folder, files(1).name));
end

function [waveformV, sampleRateHz, declaredSampleCount] = ...
        readWaveform(csvPath, pointCount, expectedSampleRateHz)
[sampleIntervalS, declaredSampleCount] = readMetadata(csvPath);
sampleRateHz = 1/sampleIntervalS;
if abs(sampleRateHz-expectedSampleRateHz)/expectedSampleRateHz > 1e-9
    error("dut:UnexpectedSampleRate", ...
        "Waveform uses %.9g S/s instead of %.9g S/s: %s", ...
        sampleRateHz, expectedSampleRateHz, csvPath);
end
if declaredSampleCount < pointCount
    error("dut:InsufficientSamples", ...
        "Waveform declares %d samples; %d are required: %s", ...
        declaredSampleCount, pointCount, csvPath);
end
rawData = readmatrix(csvPath, NumHeaderLines=6, OutputType="double");
if size(rawData, 1) < pointCount || size(rawData, 2) ~= 1
    error("dut:InvalidWaveformData", ...
        "Waveform must contain one column and at least %d rows: %s", ...
        pointCount, csvPath);
end
waveformV = rawData(1:pointCount, 1);
if any(~isfinite(waveformV))
    error("dut:NonfiniteSamples", ...
        "Waveform contains nonfinite samples: %s", csvPath);
end
end

function [sampleIntervalS, declaredSampleCount] = readMetadata(csvPath)
fileId = fopen(csvPath, "r");
if fileId < 0
    error("dut:CannotOpenWaveformFile", ...
        "Cannot open waveform file: %s", csvPath);
end
cleanup = onCleanup(@() fclose(fileId));
sectionLine = string(fgetl(fileId));
headerLine = string(fgetl(fileId));
metadataLine = string(fgetl(fileId));
if ~endsWith(strtrim(sectionLine), "Meta data", IgnoreCase=true) || ...
        ~startsWith(strtrim(headerLine), "Physical channel,", ...
        IgnoreCase=true)
    error("dut:InvalidWaveformHeader", ...
        "Unexpected waveform header: %s", csvPath);
end
fields = split(metadataLine, ",");
if numel(fields) < 4
    error("dut:InvalidWaveformHeader", ...
        "Incomplete waveform metadata: %s", csvPath);
end
sampleIntervalS = str2double(strtrim(fields(3)));
declaredSampleCount = str2double(strtrim(fields(4)));
end

function row = makeRunRow( ...
        runIndex, sourcePath, declaredSampleCount, sampleRateHz, ...
        waveformV, frequencyHz, outputPsdV2PerHz, gain)
row = emptyRunRow();
row.RunNumber = runIndex;
row.SourcePath = sourcePath;
row.DeclaredSampleCount = declaredSampleCount;
row.SampleRateHz = sampleRateHz;
row.DcMeanOutputV = mean(waveformV);
row.TimeStdOutputV = std(waveformV, 0);
row.PeakToPeakOutputV = range(waveformV);
row.MinOutputV = min(waveformV);
row.MaxOutputV = max(waveformV);
inputAsdVrtHz = sqrt(max(outputPsdV2PerHz, 0))/gain;
row.InputAsdAt1HzNVrtHz = ...
    valueAtFrequency(frequencyHz, inputAsdVrtHz, 1)*1e9;
row.MedianInputAsd1To10NVrtHz = ...
    medianBand(frequencyHz, inputAsdVrtHz, [1, 10])*1e9;
row.MedianInputAsd100To10kNVrtHz = ...
    medianBand(frequencyHz, inputAsdVrtHz, [100, 10e3])*1e9;
end

function row = emptyRunRow()
row = struct( ...
    RunNumber=0, ...
    SourcePath="", ...
    DeclaredSampleCount=0, ...
    SampleRateHz=NaN, ...
    DcMeanOutputV=NaN, ...
    TimeStdOutputV=NaN, ...
    PeakToPeakOutputV=NaN, ...
    MinOutputV=NaN, ...
    MaxOutputV=NaN, ...
    InputAsdAt1HzNVrtHz=NaN, ...
    MedianInputAsd1To10NVrtHz=NaN, ...
    MedianInputAsd100To10kNVrtHz=NaN);
end

function summary = makeConditionSummary( ...
        frequencyHz, inputAsdVrtHz, runSummary, runCount, cfg)
summary = table( ...
    runCount, cfg.gain, mean(runSummary.DcMeanOutputV), ...
    valueAtFrequency(frequencyHz, inputAsdVrtHz, 1)*1e9, ...
    medianBand(frequencyHz, inputAsdVrtHz, [0.8, 1.2])*1e9, ...
    medianBand(frequencyHz, inputAsdVrtHz, [1, 10])*1e9, ...
    medianBand(frequencyHz, inputAsdVrtHz, [10, 100])*1e9, ...
    medianBand(frequencyHz, inputAsdVrtHz, [100, 1e3])*1e9, ...
    medianBand(frequencyHz, inputAsdVrtHz, [100, 10e3])*1e9, ...
    VariableNames=[ ...
    "RunCount", "Gain", "MeanDcOutputV", ...
    "InputAsdAt1HzNVrtHz", ...
    "MedianInputAsd0p8To1p2NVrtHz", ...
    "MedianInputAsd1To10NVrtHz", ...
    "MedianInputAsd10To100NVrtHz", ...
    "MedianInputAsd100To1kNVrtHz", ...
    "MedianInputAsd100To10kNVrtHz"]);
end

function value = valueAtFrequency(frequencyHz, inputAsdVrtHz, targetHz)
[~, index] = min(abs(frequencyHz-targetHz));
value = inputAsdVrtHz(index);
end

function value = medianBand(frequencyHz, inputAsdVrtHz, limitsHz)
take = frequencyHz >= limitsHz(1) & frequencyHz <= limitsHz(2);
value = median(inputAsdVrtHz(take));
end

function plotData = reduceForPlot( ...
        frequencyHz, inputPsdV2PerHz, limitsHz, binCount)
take = frequencyHz > 0 & frequencyHz >= limitsHz(1) & ...
    frequencyHz <= limitsHz(2);
selectedFrequencyHz = frequencyHz(take);
selectedPsdV2PerHz = inputPsdV2PerHz(take);
edgesHz = logspace( ...
    log10(limitsHz(1)), log10(limitsHz(2)), binCount+1).';
binIndex = discretize(selectedFrequencyHz, edgesHz);
validBins = unique(binIndex(isfinite(binIndex)));
plotFrequencyHz = zeros(numel(validBins), 1);
plotPsdV2PerHz = zeros(numel(validBins), 1);
for outputIndex = 1:numel(validBins)
    inBin = binIndex == validBins(outputIndex);
    plotFrequencyHz(outputIndex) = exp(mean(log( ...
        selectedFrequencyHz(inBin))));
    plotPsdV2PerHz(outputIndex) = mean(selectedPsdV2PerHz(inBin));
end
plotData = struct;
plotData.frequencyHz = plotFrequencyHz;
plotData.inputPsdV2PerHz = plotPsdV2PerHz;
plotData.inputAsdVrtHz = sqrt(max(plotPsdV2PerHz, 0));
end

function figureHandle = plotSameFormat( ...
        frequencyHz, inputAsdVrtHz, cfg)
use = frequencyHz >= cfg.plotFrequencyLimitsHz(1) & ...
    frequencyHz <= cfg.plotFrequencyLimitsHz(2) & ...
    isfinite(inputAsdVrtHz) & inputAsdVrtHz > 0;
figureHandle = figure( ...
    Visible="off", Color="w", Units="pixels", ...
    Position=[100, 100, 1515, 1293], ...
    Name="DUT repeated-condition input-referred noise");
axisHandle = axes(figureHandle);
loglog(axisHandle, frequencyHz(use), inputAsdVrtHz(use)*1e9, ...
    LineWidth=1.0, Color=[0, 0.4470, 0.7410]);
hold(axisHandle, "on");
referenceLine = yline(axisHandle, cfg.referenceNvRtHz, "--", ...
    sprintf("%.1f nV/sqrt(Hz)", cfg.referenceNvRtHz), ...
    LineWidth=1.5, Color=[0.85, 0.325, 0.098]);
referenceLine.LabelHorizontalAlignment = "right";
referenceLine.LabelVerticalAlignment = "bottom";
hold(axisHandle, "off");
grid(axisHandle, "on");
grid(axisHandle, "minor");
box(axisHandle, "on");
axisHandle.Color = [1, 1, 1];
axisHandle.XColor = [0, 0, 0];
axisHandle.YColor = [0, 0, 0];
axisHandle.GridColor = [0.15, 0.15, 0.15];
axisHandle.MinorGridColor = [0.15, 0.15, 0.15];
axisHandle.FontSize = 20;
xlabel(axisHandle, "Frequency (Hz)", ...
    Color=[0, 0, 0], FontSize=26);
ylabel(axisHandle, "Input-referred noise (nV/sqrt(Hz))", ...
    Color=[0, 0, 0], FontSize=26);
title(axisHandle, {cfg.testLabel; cfg.figureSubtitle}, ...
    Color=[0, 0, 0], FontSize=28, FontWeight="bold");
referenceLine.FontSize = 20;
xlim(axisHandle, cfg.plotFrequencyLimitsHz);
end

function figureHandle = plotScreenshotComparison( ...
        initialImagePath, currentImagePath)
initialImage = imread(initialImagePath);
currentImage = imread(currentImagePath);
figureHandle = figure( ...
    Visible="off", Color="w", Units="pixels", ...
    Position=[100, 100, 3000, 1320], ...
    Name="DUT initial-versus-current noise comparison");
initialAxis = axes(figureHandle, Units="normalized", ...
    Position=[0.01, 0.02, 0.485, 0.93]);
image(initialAxis, initialImage);
axis(initialAxis, "image");
axis(initialAxis, "off");
title(initialAxis, "Initial measurement (retained screenshot)", ...
    Color=[0, 0, 0], FontSize=18, FontWeight="bold");
currentAxis = axes(figureHandle, Units="normalized", ...
    Position=[0.505, 0.02, 0.485, 0.93]);
image(currentAxis, currentImage);
axis(currentAxis, "image");
axis(currentAxis, "off");
title(currentAxis, "Current measurement (50 Ohm connected)", ...
    Color=[0, 0, 0], FontSize=18, FontWeight="bold");
end

function exportPixelSizePng(figureHandle, outputPath, pixelSize)
figureHandle.Units = "pixels";
position = figureHandle.Position;
position(3:4) = pixelSize;
figureHandle.Position = position;
outputDpi = 100;
figureHandle.PaperUnits = "inches";
figureHandle.PaperPositionMode = "manual";
figureHandle.PaperPosition = [0, 0, pixelSize/outputDpi];
figureHandle.PaperSize = pixelSize/outputDpi;
print(figureHandle, outputPath, "-dpng", sprintf("-r%d", outputDpi));
end

function paths = buildPaths(outputDir, processedDir)
paths = struct;
paths.fullAnalysisMat = fullfile( ...
    outputDir, "with50ohm_full_analysis.mat");
paths.fullSpectrumCsv = fullfile( ...
    outputDir, "with50ohm_full_average_input_asd.csv");
paths.runSummaryCsv = fullfile( ...
    outputDir, "with50ohm_run_summary.csv");
paths.conditionSummaryCsv = fullfile( ...
    outputDir, "with50ohm_condition_summary.csv");
paths.sameFormatFig = fullfile( ...
    outputDir, "with50ohm_input_referred_noise_same_format.fig");
paths.sameFormatPng = fullfile( ...
    processedDir, "with50ohm_input_referred_noise_same_format.png");
paths.comparisonPng = fullfile( ...
    processedDir, "with50ohm_vs_initial_side_by_side.png");
paths.comparisonFig = fullfile( ...
    outputDir, "with50ohm_vs_initial_side_by_side.fig");
paths.processedPlotDataMat = fullfile( ...
    processedDir, "with50ohm_plot_data.mat");
paths.processedSpectrumCsv = fullfile( ...
    processedDir, "with50ohm_plot_spectrum.csv");
paths.processedRunSummaryCsv = fullfile( ...
    processedDir, "with50ohm_run_summary.csv");
paths.processedConditionSummaryCsv = fullfile( ...
    processedDir, "with50ohm_condition_summary.csv");
end
