function result = processCampaign( ...
        dataRoot, outputDir, processedDir, cobNumbers, cfg)
%PROCESSCAMPAIGN Process repeated DUT noise captures by COB and bias.

arguments
    dataRoot (1, 1) string
    outputDir (1, 1) string
    processedDir (1, 1) string
    cobNumbers (1, :) double {mustBeInteger, mustBePositive}
    cfg (1, 1) struct
end

validateConfig(cfg);
conditionCount = numel(cobNumbers)*numel(cfg.biasCurrentsMicroA);
frequencyPointCount = floor(cfg.pointCount/2) + 1;
averageInputPsdV2PerHz = zeros(frequencyPointCount, conditionCount);
frequencyHz = zeros(frequencyPointCount, 1);
conditionKeys = strings(conditionCount, 1);
runRows = repmat(emptyRunRow(), ...
    conditionCount*cfg.runCount, 1);

conditionIndex = 0;
rowIndex = 0;
for cobNumber = cobNumbers
    for biasCurrentMicroA = cfg.biasCurrentsMicroA
        conditionIndex = conditionIndex + 1;
        conditionKeys(conditionIndex) = sprintf( ...
            "COB%d_%duA", cobNumber, biasCurrentMicroA);
        perRunOutputPsdV2PerHz = zeros( ...
            frequencyPointCount, cfg.runCount);

        for runNumber = 1:cfg.runCount
            rowIndex = rowIndex + 1;
            csvPath = resolveWaveformPath( ...
                dataRoot, cobNumber, biasCurrentMicroA, ...
                runNumber, cfg);
            [waveformV, sampleRateHz, declaredSampleCount] = ...
                readWaveform( ...
                csvPath, cfg.pointCount, cfg.sampleRateHz);
            [outputPsdV2PerHz, runFrequencyHz] = noiseSpectrum( ...
                waveformV, sampleRateHz, cfg.pointCount, false);

            if conditionIndex == 1 && runNumber == 1
                frequencyHz = runFrequencyHz;
            end
            perRunOutputPsdV2PerHz(:, runNumber) = ...
                outputPsdV2PerHz;
            runRows(rowIndex) = makeRunRow( ...
                cobNumber, biasCurrentMicroA, runNumber, csvPath, ...
                declaredSampleCount, sampleRateHz, waveformV);
        end

        averageInputPsdV2PerHz(:, conditionIndex) = ...
            mean(perRunOutputPsdV2PerHz, 2)/cfg.gain^2;
    end
end

result = struct;
result.frequencyHz = frequencyHz;
result.conditionKeys = conditionKeys;
result.averageInputPsdV2PerHz = averageInputPsdV2PerHz;
result.averageInputAsdVrtHz = sqrt( ...
    max(averageInputPsdV2PerHz, 0));
result.runSummary = struct2table(runRows);
result.conditionSummary = buildConditionSummary( ...
    result, cobNumbers, cfg);
result.outputDir = outputDir;
result.processedDir = processedDir;
[result.outputPaths, result.plotData] = exportCampaignArtifacts( ...
    result, cobNumbers, cfg);
end

function validateConfig(cfg)
requiredFields = [ ...
    "sampleRateHz", "pointCount", "runCount", "gain", ...
    "biasCurrentsMicroA", "supplyLabel", "gainLabel", ...
    "plotBinCount", "plotFrequencyLimitsHz"];
missingFields = requiredFields(~isfield(cfg, requiredFields));
if ~isempty(missingFields)
    error("dut:InvalidConfig", ...
        "DUT campaign configuration is missing: %s", ...
        strjoin(missingFields, ", "));
end
validScalar = @(value) isnumeric(value) && isscalar(value) && ...
    isfinite(value);
validPositiveInteger = @(value) validScalar(value) && ...
    value >= 1 && value == fix(value);
validLimits = isnumeric(cfg.plotFrequencyLimitsHz) && ...
    isequal(size(cfg.plotFrequencyLimitsHz), [1, 2]) && ...
    all(isfinite(cfg.plotFrequencyLimitsHz)) && ...
    all(cfg.plotFrequencyLimitsHz > 0) && ...
    cfg.plotFrequencyLimitsHz(1) < cfg.plotFrequencyLimitsHz(2);
validBiases = isnumeric(cfg.biasCurrentsMicroA) && ...
    isvector(cfg.biasCurrentsMicroA) && ...
    ~isempty(cfg.biasCurrentsMicroA) && ...
    all(isfinite(cfg.biasCurrentsMicroA)) && ...
    all(cfg.biasCurrentsMicroA > 0);
validLabels = (isstring(cfg.supplyLabel) || ischar(cfg.supplyLabel)) && ...
    strlength(string(cfg.supplyLabel)) > 0 && ...
    (isstring(cfg.gainLabel) || ischar(cfg.gainLabel)) && ...
    strlength(string(cfg.gainLabel)) > 0;
isValid = validScalar(cfg.sampleRateHz) && cfg.sampleRateHz > 0 && ...
    validPositiveInteger(cfg.pointCount) && cfg.pointCount >= 2 && ...
    validPositiveInteger(cfg.runCount) && ...
    validScalar(cfg.gain) && cfg.gain > 0 && ...
    validBiases && validLabels && ...
    validPositiveInteger(cfg.plotBinCount) && validLimits && ...
    cfg.plotFrequencyLimitsHz(2) <= cfg.sampleRateHz/2;
if ~isValid
    error("dut:InvalidConfig", ...
        "DUT campaign configuration is incomplete or invalid.");
end
end

function summary = buildConditionSummary(result, cobNumbers, cfg)
conditionCount = numel(result.conditionKeys);
rows = repmat(emptyConditionRow(), conditionCount, 1);
conditionIndex = 0;
for cobNumber = cobNumbers
    for biasCurrentMicroA = cfg.biasCurrentsMicroA
        conditionIndex = conditionIndex + 1;
        take = result.runSummary.CobNumber == cobNumber & ...
            result.runSummary.BiasCurrentMicroA == biasCurrentMicroA;
        runTable = result.runSummary(take, :);
        inputAsdVrtHz = result.averageInputAsdVrtHz(:, conditionIndex);
        inputPsdV2PerHz = result.averageInputPsdV2PerHz(:, conditionIndex);
        rows(conditionIndex) = makeConditionRow( ...
            cobNumber, biasCurrentMicroA, runTable, ...
            result.frequencyHz, inputAsdVrtHz, inputPsdV2PerHz);
    end
end
summary = struct2table(rows);
end

function row = makeConditionRow( ...
        cobNumber, biasCurrentMicroA, runTable, frequencyHz, ...
        inputAsdVrtHz, inputPsdV2PerHz)
row = emptyConditionRow();
row.CobNumber = cobNumber;
row.BiasCurrentMicroA = biasCurrentMicroA;
row.RunCount = height(runTable);
row.MeanDcOutputV = mean(runTable.DcMeanOutputV);
row.MinDcOutputV = min(runTable.DcMeanOutputV);
row.MaxDcOutputV = max(runTable.DcMeanOutputV);
row.MeanTimeStdOutputV = mean(runTable.TimeStdOutputV);
row.MeanPeakToPeakOutputV = mean(runTable.PeakToPeakOutputV);
row.MedianInputAsd0p1To10NVrtHz = medianBand( ...
    frequencyHz, inputAsdVrtHz, [0.1, 10])*1e9;
row.MedianInputAsd10To100NVrtHz = medianBand( ...
    frequencyHz, inputAsdVrtHz, [10, 100])*1e9;
row.MedianInputAsd100To1kNVrtHz = medianBand( ...
    frequencyHz, inputAsdVrtHz, [100, 1e3])*1e9;
row.MedianInputAsd1kTo10kNVrtHz = medianBand( ...
    frequencyHz, inputAsdVrtHz, [1e3, 1e4])*1e9;
row.MedianInputAsd10kTo25kNVrtHz = medianBand( ...
    frequencyHz, inputAsdVrtHz, [1e4, 2.5e4])*1e9;
row.IntegratedInputNoise0p1To10UVrms = integrateBand( ...
    frequencyHz, inputPsdV2PerHz, [0.1, 10])*1e6;
row.IntegratedInputNoise0p1To100UVrms = integrateBand( ...
    frequencyHz, inputPsdV2PerHz, [0.1, 100])*1e6;
end

function value = medianBand(frequencyHz, inputAsdVrtHz, limitsHz)
take = frequencyHz >= limitsHz(1) & frequencyHz <= limitsHz(2);
if any(take)
    value = median(inputAsdVrtHz(take));
else
    value = NaN;
end
end

function value = integrateBand(frequencyHz, inputPsdV2PerHz, limitsHz)
take = frequencyHz >= limitsHz(1) & frequencyHz <= limitsHz(2);
if nnz(take) >= 2
    value = sqrt(max(trapz( ...
        frequencyHz(take), inputPsdV2PerHz(take)), 0));
else
    value = NaN;
end
end

function csvPath = resolveWaveformPath( ...
        dataRoot, cobNumber, biasCurrentMicroA, runNumber, cfg)
conditionName = sprintf("NO.%d_%s_%s_Ibias_%duA", ...
    cobNumber, cfg.supplyLabel, cfg.gainLabel, biasCurrentMicroA);
runDir = fullfile(dataRoot, conditionName, ...
    sprintf("run_%02d", runNumber));
files = dir(fullfile(runDir, "*Waveform Data.csv"));
if isempty(files)
    error("dut:MissingWaveformFile", ...
        "COB %d, %g uA, run %02d has no Waveform Data CSV: %s", ...
        cobNumber, biasCurrentMicroA, runNumber, runDir);
end
if numel(files) ~= 1
    error("dut:AmbiguousWaveformFile", ...
        "COB %d, %g uA, run %02d must contain exactly one " + ...
        "Waveform Data CSV: %s", ...
        cobNumber, biasCurrentMicroA, runNumber, runDir);
end
csvPath = string(fullfile(runDir, files(1).name));
end

function [waveformV, sampleRateHz, declaredSampleCount] = ...
        readWaveform(csvPath, pointCount, expectedSampleRateHz)
fileId = fopen(csvPath, "r");
if fileId < 0
    error("dut:CannotOpenWaveformFile", ...
        "Cannot open waveform CSV: %s", csvPath);
end
cleanup = onCleanup(@() fclose(fileId));
sectionLine = string(fgetl(fileId));
headerLine = string(fgetl(fileId));
metadataLine = string(fgetl(fileId));
metadataFields = split(metadataLine, ",");
if ~endsWith(strtrim(sectionLine), "Meta data", IgnoreCase=true) || ...
        ~startsWith(strtrim(headerLine), "Physical channel,", ...
        IgnoreCase=true) || numel(metadataFields) < 4
    error("dut:InvalidWaveformHeader", ...
        "Unexpected or incomplete waveform metadata: %s", csvPath);
end
sampleIntervalS = str2double(strtrim(metadataFields(3)));
declaredSampleCount = str2double(strtrim(metadataFields(4)));
if ~(isfinite(sampleIntervalS) && sampleIntervalS > 0 && ...
        isfinite(declaredSampleCount) && declaredSampleCount >= 0 && ...
        declaredSampleCount == fix(declaredSampleCount))
    error("dut:InvalidWaveformHeader", ...
        "Waveform metadata values are invalid: %s", csvPath);
end
if declaredSampleCount < pointCount
    error("dut:InsufficientSamples", ...
        "Waveform declares %d samples; %d are required: %s", ...
        declaredSampleCount, pointCount, csvPath);
end
sampleRateHz = 1/sampleIntervalS;
if ~(isfinite(sampleRateHz) && sampleRateHz > 0) || ...
        abs(sampleRateHz-expectedSampleRateHz)/expectedSampleRateHz > 1e-9
    error("dut:UnexpectedSampleRate", ...
        "Waveform uses %.9g S/s; %.9g S/s are required: %s", ...
        sampleRateHz, expectedSampleRateHz, csvPath);
end
rawData = readmatrix(csvPath, NumHeaderLines=6, OutputType="double");
if isempty(rawData) || size(rawData, 2) ~= 1
    error("dut:InvalidWaveformData", ...
        "Waveform must contain exactly one numeric column: %s", ...
        csvPath);
end
if size(rawData, 1) < pointCount
    error("dut:InsufficientSamples", ...
        "Waveform contains %d readable samples; %d are required: %s", ...
        size(rawData, 1), pointCount, csvPath);
end
waveformV = rawData(1:pointCount, 1);
if any(~isfinite(waveformV))
    error("dut:NonfiniteSamples", ...
        "First %d waveform samples must all be finite: %s", ...
        pointCount, csvPath);
end
end

function row = makeRunRow( ...
        cobNumber, biasCurrentMicroA, runNumber, csvPath, ...
        declaredSampleCount, sampleRateHz, waveformV)
row = emptyRunRow();
row.CobNumber = cobNumber;
row.BiasCurrentMicroA = biasCurrentMicroA;
row.RunNumber = runNumber;
row.SourcePath = csvPath;
row.DeclaredSampleCount = declaredSampleCount;
row.SampleRateHz = sampleRateHz;
row.DcMeanOutputV = mean(waveformV);
row.TimeStdOutputV = std(waveformV, 0);
row.PeakToPeakOutputV = max(waveformV)-min(waveformV);
end

function row = emptyRunRow()
row = struct( ...
    CobNumber=0, ...
    BiasCurrentMicroA=0, ...
    RunNumber=0, ...
    SourcePath="", ...
    DeclaredSampleCount=0, ...
    SampleRateHz=0, ...
    DcMeanOutputV=0, ...
    TimeStdOutputV=0, ...
    PeakToPeakOutputV=0);
end

function row = emptyConditionRow()
row = struct( ...
    CobNumber=0, ...
    BiasCurrentMicroA=0, ...
    RunCount=0, ...
    MeanDcOutputV=0, ...
    MinDcOutputV=0, ...
    MaxDcOutputV=0, ...
    MeanTimeStdOutputV=0, ...
    MeanPeakToPeakOutputV=0, ...
    MedianInputAsd0p1To10NVrtHz=NaN, ...
    MedianInputAsd10To100NVrtHz=NaN, ...
    MedianInputAsd100To1kNVrtHz=NaN, ...
    MedianInputAsd1kTo10kNVrtHz=NaN, ...
    MedianInputAsd10kTo25kNVrtHz=NaN, ...
    IntegratedInputNoise0p1To10UVrms=NaN, ...
    IntegratedInputNoise0p1To100UVrms=NaN);
end
