function paths = replayRepeatedCondition(processedDir)
%REPLAYREPEATEDCONDITION Regenerate 50 Ohm evidence figures from compact data.

arguments
    processedDir (1, 1) string
end

matPath = fullfile(processedDir, "with50ohm_plot_data.mat");
initialImagePath = fullfile( ...
    processedDir, "initial_measurement_reference.png");
if ~isfile(matPath) || ~isfile(initialImagePath)
    error("dut:MissingProcessedData", ...
        "Repeated-condition MAT or initial reference image is missing: %s", ...
        processedDir);
end
saved = load(matPath);
requiredFields = [ ...
    "plotFrequencyHz", "plotInputAsdVrtHz", "runCount", "cfg"];
if ~all(isfield(saved, requiredFields)) || ...
        ~isfield(saved.cfg, "plotFrequencyLimitsHz") || ...
        ~isfield(saved.cfg, "referenceNvRtHz") || ...
        ~isfield(saved.cfg, "testLabel") || ...
        ~isfield(saved.cfg, "figureSubtitle")
    error("dut:InvalidProcessedData", ...
        "Compact repeated-condition data is missing required fields: %s", ...
        matPath);
end

frequencyHz = saved.plotFrequencyHz(:);
inputAsdVrtHz = saved.plotInputAsdVrtHz(:);
limitsHz = saved.cfg.plotFrequencyLimitsHz;
validData = numel(frequencyHz) == numel(inputAsdVrtHz) && ...
    all(isfinite(frequencyHz)) && all(frequencyHz > 0) && ...
    issorted(frequencyHz, "strictascend") && ...
    all(isfinite(inputAsdVrtHz)) && all(inputAsdVrtHz > 0) && ...
    isnumeric(limitsHz) && isequal(size(limitsHz), [1, 2]) && ...
    all(isfinite(limitsHz)) && all(limitsHz > 0) && ...
    limitsHz(1) < limitsHz(2) && ...
    isnumeric(saved.cfg.referenceNvRtHz) && ...
    isscalar(saved.cfg.referenceNvRtHz) && ...
    isfinite(saved.cfg.referenceNvRtHz) && ...
    saved.cfg.referenceNvRtHz > 0;
if ~validData
    error("dut:InvalidProcessedData", ...
        "Compact repeated-condition arrays are invalid: %s", matPath);
end

paths = struct;
paths.sameFormatPng = fullfile( ...
    processedDir, "with50ohm_input_referred_noise_replayed.png");
paths.comparisonPng = fullfile( ...
    processedDir, "with50ohm_vs_initial_replayed_side_by_side.png");

spectrumFigure = plotSpectrum(frequencyHz, inputAsdVrtHz, saved.cfg);
spectrumCleanup = onCleanup(@() close(spectrumFigure));
exportPixelSizePng( ...
    spectrumFigure, paths.sameFormatPng, [1515, 1293]);

comparisonFigure = plotComparison( ...
    initialImagePath, paths.sameFormatPng);
comparisonCleanup = onCleanup(@() close(comparisonFigure));
exportPixelSizePng( ...
    comparisonFigure, paths.comparisonPng, [3000, 1320]);
end

function figureHandle = plotSpectrum(frequencyHz, inputAsdVrtHz, cfg)
figureHandle = figure( ...
    Visible="off", Color="w", Units="pixels", ...
    Position=[100, 100, 1515, 1293], ...
    Name="DUT repeated-condition compact replay");
axisHandle = axes(figureHandle);
loglog(axisHandle, frequencyHz, inputAsdVrtHz*1e9, ...
    LineWidth=1.0, Color=[0, 0.4470, 0.7410]);
hold(axisHandle, "on");
referenceLine = yline(axisHandle, cfg.referenceNvRtHz, "--", ...
    sprintf("%.1f nV/sqrt(Hz)", cfg.referenceNvRtHz), ...
    LineWidth=1.5, Color=[0.85, 0.325, 0.098]);
referenceLine.LabelHorizontalAlignment = "right";
referenceLine.LabelVerticalAlignment = "bottom";
hold(axisHandle, "off");
set(axisHandle, ...
    XScale="log", YScale="log", Color="w", ...
    XColor="k", YColor="k", FontSize=20, ...
    GridColor=[0.15, 0.15, 0.15], ...
    MinorGridColor=[0.15, 0.15, 0.15], Box="on");
grid(axisHandle, "on");
grid(axisHandle, "minor");
xlim(axisHandle, cfg.plotFrequencyLimitsHz);
xlabel(axisHandle, "Frequency (Hz)", FontSize=26, Color="k");
ylabel(axisHandle, "Input-referred noise (nV/sqrt(Hz))", ...
    FontSize=26, Color="k");
title(axisHandle, {cfg.testLabel; cfg.figureSubtitle}, ...
    FontSize=28, FontWeight="bold", Color="k");
referenceLine.FontSize = 20;
end

function figureHandle = plotComparison(initialImagePath, currentImagePath)
initialImage = imread(initialImagePath);
currentImage = imread(currentImagePath);
figureHandle = figure( ...
    Visible="off", Color="w", Units="pixels", ...
    Position=[100, 100, 3000, 1320], ...
    Name="DUT initial-versus-current compact replay");
initialAxis = axes(figureHandle, Units="normalized", ...
    Position=[0.01, 0.02, 0.485, 0.93]);
image(initialAxis, initialImage);
axis(initialAxis, "image");
axis(initialAxis, "off");
title(initialAxis, "Initial measurement (retained screenshot)", ...
    Color="k", FontSize=18, FontWeight="bold");
currentAxis = axes(figureHandle, Units="normalized", ...
    Position=[0.505, 0.02, 0.485, 0.93]);
image(currentAxis, currentImage);
axis(currentAxis, "image");
axis(currentAxis, "off");
title(currentAxis, "Current measurement (compact replay)", ...
    Color="k", FontSize=18, FontWeight="bold");
end

function exportPixelSizePng(figureHandle, outputPath, pixelSize)
figureHandle.Units = "pixels";
position = figureHandle.Position;
position(3:4) = pixelSize;
figureHandle.Position = position;
outputDpi = 100;
figureHandle.PaperUnits = "inches";
figureHandle.PaperPositionMode = "manual";
figureHandle.PaperPosition = [0, 0, pixelSize/outputDpi];
figureHandle.PaperSize = pixelSize/outputDpi;
print(figureHandle, outputPath, "-dpng", ...
    sprintf("-r%d", outputDpi));
end
