function paths = replaySupplyComparison(processedDir)
%REPLAYSUPPLYCOMPARISON Regenerate the supply-comparison PNG from compact data.

arguments
    processedDir (1, 1) string
end

matPath = fullfile(processedDir, "supply_voltage_plot_data.mat");
if ~isfile(matPath)
    error("dut:MissingProcessedData", ...
        "Compact supply-comparison data does not exist: %s", matPath);
end
saved = load(matPath);
requiredFields = [ ...
    "plotF", "plotA", "conditionLabels", "referenceNvRtHz"];
if ~all(isfield(saved, requiredFields))
    error("dut:InvalidProcessedData", ...
        "Compact supply-comparison data is missing required fields: %s", ...
        matPath);
end

frequencyHz = saved.plotF(:);
inputAsdNvRtHz = saved.plotA;
conditionLabels = string(saved.conditionLabels(:));
validData = isnumeric(inputAsdNvRtHz) && ...
    size(inputAsdNvRtHz, 1) == numel(frequencyHz) && ...
    size(inputAsdNvRtHz, 2) == 2 && ...
    numel(conditionLabels) == 2 && ...
    all(isfinite(frequencyHz)) && all(frequencyHz > 0) && ...
    issorted(frequencyHz, "strictascend") && ...
    all(isfinite(inputAsdNvRtHz), "all") && ...
    all(inputAsdNvRtHz > 0, "all") && ...
    isnumeric(saved.referenceNvRtHz) && ...
    isscalar(saved.referenceNvRtHz) && ...
    isfinite(saved.referenceNvRtHz) && saved.referenceNvRtHz > 0;
if ~validData
    error("dut:InvalidProcessedData", ...
        "Compact supply-comparison arrays are invalid: %s", matPath);
end

figureHandle = figure(Visible="off", Color="w", Units="pixels", ...
    Position=[100, 100, 1800, 1100], ...
    Name="DUT supply-voltage comparison replay");
cleanup = onCleanup(@() close(figureHandle));
axisHandle = axes(figureHandle, Units="normalized", ...
    Position=[0.10, 0.13, 0.86, 0.68]);
firstLine = loglog(axisHandle, frequencyHz, inputAsdNvRtHz(:, 1), ...
    LineWidth=1.45, Color=[0, 0.4470, 0.7410], ...
    DisplayName=conditionLabels(1));
hold(axisHandle, "on");
secondLine = loglog(axisHandle, frequencyHz, inputAsdNvRtHz(:, 2), ...
    LineWidth=1.45, Color=[0.6350, 0.0780, 0.1840], ...
    DisplayName=conditionLabels(2));
referenceLine = yline(axisHandle, saved.referenceNvRtHz, "--", ...
    LineWidth=1.5, Color=[0.85, 0.325, 0.098], ...
    DisplayName=sprintf("OPA189 typ. %.1f nV/sqrt(Hz)", ...
    saved.referenceNvRtHz));
hold(axisHandle, "off");
set(axisHandle, ...
    XScale="log", YScale="log", Color="w", ...
    XColor="k", YColor="k", FontSize=18, ...
    GridColor=[0.15, 0.15, 0.15], ...
    MinorGridColor=[0.15, 0.15, 0.15], Box="on");
grid(axisHandle, "on");
grid(axisHandle, "minor");
xlim(axisHandle, [min(frequencyHz), max(frequencyHz)]);
ylim(axisHandle, [1, 1e3]);
xlabel(axisHandle, "Frequency (Hz)", FontSize=24);
ylabel(axisHandle, "Input-referred noise (nV/sqrt(Hz))", FontSize=24);
legend(axisHandle, [firstLine, secondLine, referenceLine], ...
    Orientation="horizontal", NumColumns=3, ...
    Position=[0.18, 0.825, 0.66, 0.045], ...
    FontSize=15, Color="w", TextColor="k", ...
    EdgeColor=[0.35, 0.35, 0.35]);
annotation(figureHandle, "textbox", [0.08, 0.905, 0.88, 0.08], ...
    String={ ...
    "Unicorn COB RevA DUT provisional supply-voltage comparison"; ...
    "PXI-5922, 1001x gain, DC coupling, Ib2 = Ib3 = 1 uA"}, ...
    HorizontalAlignment="center", VerticalAlignment="middle", ...
    EdgeColor="none", FontSize=24, FontWeight="bold", Color="k");

paths = struct;
paths.comparisonPng = fullfile( ...
    processedDir, "supply_voltage_comparison.png");
exportPixelSizePng(figureHandle, paths.comparisonPng, [1800, 1100]);
end

function exportPixelSizePng(figureHandle, outputPath, pixelSize)
figureHandle.Units = "pixels";
position = figureHandle.Position;
position(3:4) = pixelSize;
figureHandle.Position = position;
outputDpi = 100;
figureHandle.PaperUnits = "inches";
figureHandle.PaperPositionMode = "manual";
figureHandle.PaperPosition = [0, 0, pixelSize/outputDpi];
figureHandle.PaperSize = pixelSize/outputDpi;
print(figureHandle, outputPath, "-dpng", ...
    sprintf("-r%d", outputDpi));
end
