function exportComparisonFigures(comparison, outputPaths)
%EXPORTCOMPARISONFIGURES Export formal four-line and shielded-only plots.

exportOneFigure(comparison, 1:4, ...
    outputPaths.fourConditionFigurePath, ...
    "OPA189 ±3 V / ±18 V 噪声对比（每条件 10 次 PSD 平均）");
exportOneFigure(comparison, [2, 4], ...
    outputPaths.shieldedFigurePath, ...
    "OPA189 带屏蔽罩：±3 V 与 ±18 V 噪声对比（每条件 10 次 PSD 平均）");
end

function exportOneFigure(comparison, selectedIndices, figurePath, titleText)
results = comparison.results;
frequencyHz = results(1).frequencyHz;
conditionCount = numel(selectedIndices);
inputAsdNVrtHz = zeros(numel(frequencyHz), conditionCount);
for plotIndex = 1:conditionCount
    inputAsdNVrtHz(:, plotIndex) = ...
        results(selectedIndices(plotIndex)).inputAsdVrtHz*1e9;
end

figureHandle = figure("Visible", "off", "Color", "w", ...
    "Position", [100, 100, 1250, 720]);
cleanup = onCleanup(@() close(figureHandle));
if ~isempty(which("theme"))
    theme(figureHandle, "light");
end
axesHandle = axes(figureHandle);
configureWhiteAxes(axesHandle);
hold(axesHandle, "on");

colors = [ ...
    0.0000, 0.4470, 0.7410; ...
    0.0000, 0.4470, 0.7410; ...
    0.8500, 0.3250, 0.0980; ...
    0.8500, 0.3250, 0.0980];
lineStyles = {"--", "-", "--", "-"};
if isequal(selectedIndices, [2, 4])
    lineStyles = {"-", "-"};
    colors = colors(selectedIndices, :);
end
lineHandles = gobjects(conditionCount, 1);
for plotIndex = 1:conditionCount
    lineHandles(plotIndex) = loglog(axesHandle, frequencyHz, ...
        inputAsdNVrtHz(:, plotIndex), ...
        "Color", colors(plotIndex, :), ...
        "LineStyle", lineStyles{plotIndex}, ...
        "LineWidth", 1.9);
end
yline(axesHandle, 5.2, "--", "OPA189 典型值 5.2 nV/\surdHz", ...
    "Color", [0.35, 0.35, 0.35], ...
    "LabelHorizontalAlignment", "left", ...
    "HandleVisibility", "off");
xline(axesHandle, 50, ":", "50 Hz", ...
    "Color", [0.65, 0.10, 0.10], ...
    "LabelVerticalAlignment", "bottom", ...
    "HandleVisibility", "off");
set(axesHandle, "XScale", "log", "YScale", "log");
xlim(axesHandle, [0.1, 100]);
xlabel(axesHandle, "频率 (Hz)");
ylabel(axesHandle, "输入等效 ASD (nV/\surdHz)");
title(axesHandle, titleText);
legendHandle = legend(axesHandle, lineHandles, ...
    cellstr(comparison.conditionLabels(selectedIndices)), ...
    "Location", "best");
set(legendHandle, "Color", "w", "TextColor", "k", ...
    "EdgeColor", [0.35, 0.35, 0.35], "Interpreter", "none");
set(figureHandle, "PaperPositionMode", "auto");
print(figureHandle, figurePath, "-dpng", "-r200");
end

function configureWhiteAxes(axesHandle)
set(axesHandle, ...
    "Color", "w", ...
    "XColor", [0.15, 0.15, 0.15], ...
    "YColor", [0.15, 0.15, 0.15], ...
    "GridColor", [0.72, 0.72, 0.72], ...
    "MinorGridColor", [0.84, 0.84, 0.84], ...
    "GridAlpha", 0.45, ...
    "MinorGridAlpha", 0.30, ...
    "FontSize", 12, ...
    "LineWidth", 0.9, ...
    "Box", "on");
grid(axesHandle, "on");
grid(axesHandle, "minor");
end
