function [paths, plotData] = exportCampaignArtifacts( ...
        result, cobNumbers, cfg)
%EXPORTCAMPAIGNARTIFACTS Write full local and compact processed results.

if ~isfolder(result.outputDir)
    mkdir(result.outputDir);
end
if ~isfolder(result.processedDir)
    mkdir(result.processedDir);
end

paths = buildPaths(result.outputDir, result.processedDir);
fullSpectrum = makeSpectrumTable( ...
    result.frequencyHz, result.averageInputAsdVrtHz, ...
    result.conditionKeys);
writetable(fullSpectrum, paths.fullSpectrumCsv);
writetable(result.runSummary, paths.runSummaryCsv);
writetable(result.conditionSummary, paths.conditionSummaryCsv);

frequencyHz = result.frequencyHz;
conditionKeys = result.conditionKeys;
averageInputPsdV2PerHz = result.averageInputPsdV2PerHz;
averageInputAsdVrtHz = result.averageInputAsdVrtHz;
runSummary = result.runSummary;
conditionSummary = result.conditionSummary;
save(paths.fullAnalysisMat, ...
    "frequencyHz", "conditionKeys", ...
    "averageInputPsdV2PerHz", "averageInputAsdVrtHz", ...
    "runSummary", "conditionSummary", "cobNumbers", "cfg", ...
    "-v7.3");

plotData = reduceForPlot( ...
    result.frequencyHz, result.averageInputPsdV2PerHz, ...
    cfg.plotFrequencyLimitsHz, cfg.plotBinCount);
plotSpectrum = makeSpectrumTable( ...
    plotData.frequencyHz, plotData.inputAsdVrtHz, ...
    result.conditionKeys);
writetable(plotSpectrum, paths.plotSpectrumCsv);
processedRunSummary = result.runSummary;
processedRunSummary.SourcePath(:) = ...
    "[raw waveform omitted; see data/raw/README.md]";
writetable(processedRunSummary, paths.processedRunSummaryCsv);
writetable(result.conditionSummary, ...
    paths.processedConditionSummaryCsv);

plotFrequencyHz = plotData.frequencyHz;
plotInputPsdV2PerHz = plotData.inputPsdV2PerHz;
plotInputAsdVrtHz = plotData.inputAsdVrtHz;
runSummary = processedRunSummary;
save(paths.plotDataMat, ...
    "plotFrequencyHz", "plotInputPsdV2PerHz", ...
    "plotInputAsdVrtHz", "conditionKeys", ...
    "runSummary", "conditionSummary", "cobNumbers", "cfg");

writeCampaignFigures( ...
    plotData, result.conditionKeys, cobNumbers, cfg, paths);
end

function paths = buildPaths(outputDir, processedDir)
paths = struct;
paths.fullAnalysisMat = fullfile( ...
    outputDir, "dut_noise_full_analysis.mat");
paths.fullSpectrumCsv = fullfile( ...
    outputDir, "dut_noise_full_average_input_asd.csv");
paths.runSummaryCsv = fullfile( ...
    outputDir, "dut_noise_run_summary.csv");
paths.conditionSummaryCsv = fullfile( ...
    outputDir, "dut_noise_condition_summary.csv");
paths.byCobFig = fullfile(outputDir, "dut_noise_by_cob.fig");
paths.byBiasFig = fullfile(outputDir, "dut_noise_by_bias.fig");
paths.plotDataMat = fullfile( ...
    processedDir, "dut_noise_plot_data.mat");
paths.plotSpectrumCsv = fullfile( ...
    processedDir, "dut_noise_plot_spectra.csv");
paths.processedRunSummaryCsv = fullfile( ...
    processedDir, "dut_noise_run_summary.csv");
paths.processedConditionSummaryCsv = fullfile( ...
    processedDir, "dut_noise_condition_summary.csv");
paths.byCobPng = fullfile( ...
    processedDir, "dut_noise_by_cob.png");
paths.byBiasPng = fullfile( ...
    processedDir, "dut_noise_by_bias.png");
end

function spectrum = makeSpectrumTable( ...
        frequencyHz, inputAsdVrtHz, conditionKeys)
spectrum = table(frequencyHz, VariableNames="Frequency_Hz");
for conditionIndex = 1:numel(conditionKeys)
    variableName = matlab.lang.makeValidName( ...
        conditionKeys(conditionIndex) + ...
        "_Input_ASD_nV_per_sqrtHz");
    spectrum.(variableName) = inputAsdVrtHz(:, conditionIndex)*1e9;
end
end

function plotData = reduceForPlot( ...
        frequencyHz, inputPsdV2PerHz, limitsHz, binCount)
positiveFrequencyHz = frequencyHz( ...
    frequencyHz > 0 & frequencyHz >= limitsHz(1) & ...
    frequencyHz <= limitsHz(2));
edgesHz = logspace( ...
    log10(limitsHz(1)), log10(limitsHz(2)), binCount+1).';
binIndex = discretize(positiveFrequencyHz, edgesHz);
validBins = unique(binIndex(isfinite(binIndex)));

plotFrequencyHz = zeros(numel(validBins), 1);
plotInputPsdV2PerHz = zeros( ...
    numel(validBins), size(inputPsdV2PerHz, 2));
fullTake = frequencyHz > 0 & frequencyHz >= limitsHz(1) & ...
    frequencyHz <= limitsHz(2);
selectedPsd = inputPsdV2PerHz(fullTake, :);
for outputIndex = 1:numel(validBins)
    take = binIndex == validBins(outputIndex);
    plotFrequencyHz(outputIndex) = exp(mean( ...
        log(positiveFrequencyHz(take))));
    plotInputPsdV2PerHz(outputIndex, :) = ...
        mean(selectedPsd(take, :), 1);
end

plotData = struct;
plotData.frequencyHz = plotFrequencyHz;
plotData.inputPsdV2PerHz = plotInputPsdV2PerHz;
plotData.inputAsdVrtHz = sqrt(max(plotInputPsdV2PerHz, 0));
end
