%% Compare 1.2x-current woShield noise against nominal-current woShield
% The comparison uses saved PSD results generated with identical settings.

if exist("analysisProfileOverride", "var")
    analysisProfile = lower(strtrim(string(analysisProfileOverride)));
else
    analysisProfile = "welch_8s_50pct";
end
clearvars -except analysisProfile;
close all;
clc;

scriptPath = string(mfilename("fullpath"));
assert(strlength(scriptPath) > 0, ...
    "Run this file as a MATLAB script so paths can be resolved.");
currentFolder = string(fileparts(scriptPath));
repoFolder = string(fileparts(currentFolder));
nominalFolder = fullfile(repoFolder, ...
    "Unicorn_CSA_RevA-COB_woShiled_20260828");

switch analysisProfile
    case {"whole_record_22s", "whole-record"}
        analysisProfile = "whole_record_22s";
        resultRelativeFolder = "analysis_results";
        methodLabel = "22 s whole-record";
    case {"welch_8s_50pct", "fixed-duration"}
        analysisProfile = "welch_8s_50pct";
        resultRelativeFolder = fullfile( ...
            "analysis_results", "welch_8s_50pct");
        methodLabel = "8 s Welch, 50% overlap";
    otherwise
        error("Unknown analysis profile '%s'.", analysisProfile);
end

outputFolder = fullfile(currentFolder, resultRelativeFolder);
currentPath = fullfile(outputFolder, "Average_FFT.mat");
nominalPath = fullfile(nominalFolder, resultRelativeFolder, ...
    "Average_FFT.mat");
assert(isfile(currentPath), ...
    "1.2x-current result was not found: %s", currentPath);
assert(isfile(nominalPath), ...
    "Nominal-current result was not found: %s", nominalPath);

current = load(currentPath);
nominal = load(nominalPath);
currentRuns = load(fullfile(outputFolder, "All_20_Runs_FFT.mat"), ...
    "frequencyHz", "psdV2PerHzByRun", "runNumbers");
nominalRuns = load(fullfile(nominalFolder, resultRelativeFolder, ...
    "All_20_Runs_FFT.mat"), "frequencyHz", ...
    "psdV2PerHzByRun", "runNumbers");
assert(isequal(current.frequencyHz, nominal.frequencyHz), ...
    "Full-resolution frequency grids do not match.");
assert(isequal(current.frequencyHz, currentRuns.frequencyHz) && ...
    isequal(nominal.frequencyHz, nominalRuns.frequencyHz), ...
    "Saved per-run and average frequency grids do not match.");
assert(size(currentRuns.psdV2PerHzByRun, 2) == 20 && ...
    size(nominalRuns.psdV2PerHzByRun, 2) == 20, ...
    "Both comparisons require 20 saved per-run PSD estimates.");
assert(isequal(current.octaveFrequencyHz, ...
    nominal.octaveFrequencyHz), ...
    "Fractional-octave frequency grids do not match.");
assertMatchingAnalysisSettings(current.analysisSettings, ...
    nominal.analysisSettings, analysisProfile);

targetFrequencyHz = [1; 10; 1e3];
metricName = ["ASD centered at 1 Hz"; ...
    "ASD centered at 10 Hz"; ...
    "ASD centered at 1 kHz"; ...
    "Band RMS-ASD, 1 Hz-10 Hz"; ...
    "Band RMS-ASD, 10 Hz-100 Hz"; ...
    "Band RMS-ASD, 100 Hz-1 kHz"; ...
    "Integrated noise, 1 Hz-1 kHz"; ...
    "Integrated noise, 1 Hz-25 kHz"; ...
    "Peak ASD near 50 Hz"; ...
    "Integrated 50 Hz spur, 49.5 Hz-50.5 Hz"; ...
    "Peak ASD near 150 Hz"; ...
    "Integrated 150 Hz spur, 149.5 Hz-150.5 Hz"];
unit = [repmat("V/sqrt(Hz)", 6, 1); repmat("Vrms", 2, 1); ...
    "V/sqrt(Hz)"; "Vrms"; "V/sqrt(Hz)"; "Vrms"];

currentValue = zeros(numel(metricName), 1);
nominalValue = zeros(numel(metricName), 1);
for index = 1:numel(targetFrequencyHz)
    currentValue(index) = centeredFractionalOctaveAsd( ...
        current.frequencyHz, current.ensemblePsdV2PerHz, ...
        targetFrequencyHz(index), 12);
    nominalValue(index) = centeredFractionalOctaveAsd( ...
        nominal.frequencyHz, nominal.ensemblePsdV2PerHz, ...
        targetFrequencyHz(index), 12);
end

bandsHz = [1, 10; 10, 100; 100, 1e3];
for bandIndex = 1:size(bandsHz, 1)
    metricIndex = 3+bandIndex;
    currentValue(metricIndex) = bandRmsAsd(current.frequencyHz, ...
        current.ensemblePsdV2PerHz, bandsHz(bandIndex, 1), ...
        bandsHz(bandIndex, 2));
    nominalValue(metricIndex) = bandRmsAsd(nominal.frequencyHz, ...
        nominal.ensemblePsdV2PerHz, bandsHz(bandIndex, 1), ...
        bandsHz(bandIndex, 2));
end

currentValue(7) = integrateNoise(current.frequencyHz, ...
    current.ensemblePsdV2PerHz, 1, 1e3);
nominalValue(7) = integrateNoise(nominal.frequencyHz, ...
    nominal.ensemblePsdV2PerHz, 1, 1e3);
currentValue(8) = integrateNoise(current.frequencyHz, ...
    current.ensemblePsdV2PerHz, 1, 25e3);
nominalValue(8) = integrateNoise(nominal.frequencyHz, ...
    nominal.ensemblePsdV2PerHz, 1, 25e3);
currentValue(9) = peakAsdInBand(current.frequencyHz, ...
    current.ensembleAsdVPerSqrtHz, 49, 51);
nominalValue(9) = peakAsdInBand(nominal.frequencyHz, ...
    nominal.ensembleAsdVPerSqrtHz, 49, 51);
currentValue(10) = integrateNoise(current.frequencyHz, ...
    current.ensemblePsdV2PerHz, 49.5, 50.5);
nominalValue(10) = integrateNoise(nominal.frequencyHz, ...
    nominal.ensemblePsdV2PerHz, 49.5, 50.5);
currentValue(11) = peakAsdInBand(current.frequencyHz, ...
    current.ensembleAsdVPerSqrtHz, 149, 151);
nominalValue(11) = peakAsdInBand(nominal.frequencyHz, ...
    nominal.ensembleAsdVPerSqrtHz, 149, 151);
currentValue(12) = integrateNoise(current.frequencyHz, ...
    current.ensemblePsdV2PerHz, 149.5, 150.5);
nominalValue(12) = integrateNoise(nominal.frequencyHz, ...
    nominal.ensemblePsdV2PerHz, 149.5, 150.5);

changePercent = 100*(currentValue./nominalValue-1);
currentVsNominalDb = 20*log10(currentValue./nominalValue);

% Estimate the repeatability-only confidence interval from the 20
% independent per-run power estimates in each condition.  The interval is
% calculated in log power and converted back to amplitude dB.  It does not
% include systematic error from sequential test conditions.
currentRunValue = zeros(numel(metricName), 20);
nominalRunValue = zeros(numel(metricName), 20);
for runIndex = 1:20
    currentRunValue(:, runIndex) = calculateAmplitudeMetrics( ...
        currentRuns.frequencyHz, ...
        currentRuns.psdV2PerHzByRun(:, runIndex));
    nominalRunValue(:, runIndex) = calculateAmplitudeMetrics( ...
        nominalRuns.frequencyHz, ...
        nominalRuns.psdV2PerHzByRun(:, runIndex));
end
repeatability95LowDb = nan(numel(metricName), 1);
repeatability95HighDb = nan(numel(metricName), 1);
repeatability95LowPercent = nan(numel(metricName), 1);
repeatability95HighPercent = nan(numel(metricName), 1);
powerAverageMetric = [true(8, 1); false; true; false; true];
for metricIndex = find(powerAverageMetric).'
    currentPowerByRun = currentRunValue(metricIndex, :).^2;
    nominalPowerByRun = nominalRunValue(metricIndex, :).^2;
    currentMeanPower = mean(currentPowerByRun);
    nominalMeanPower = mean(nominalPowerByRun);
    logAmplitudeRatio = 0.5*log( ...
        currentMeanPower/nominalMeanPower);
    logAmplitudeStandardError = 0.5*sqrt( ...
        var(currentPowerByRun)/(numel(currentPowerByRun)* ...
        currentMeanPower^2) + ...
        var(nominalPowerByRun)/(numel(nominalPowerByRun)* ...
        nominalMeanPower^2));
    logLow = logAmplitudeRatio-1.96*logAmplitudeStandardError;
    logHigh = logAmplitudeRatio+1.96*logAmplitudeStandardError;
    repeatability95LowDb(metricIndex) = 20/log(10)*logLow;
    repeatability95HighDb(metricIndex) = 20/log(10)*logHigh;
    repeatability95LowPercent(metricIndex) = 100*(exp(logLow)-1);
    repeatability95HighPercent(metricIndex) = 100*(exp(logHigh)-1);
end
keyMetricComparison = table(metricName, currentValue, nominalValue, ...
    unit, changePercent, currentVsNominalDb, ...
    repeatability95LowPercent, repeatability95HighPercent, ...
    repeatability95LowDb, repeatability95HighDb, ...
    VariableNames=["Metric", "Current1p2_Value", ...
    "NominalCurrent_Value", "Unit", "Change_Percent", ...
    "Current1p2_vs_Nominal_dB", ...
    "Repeatability95_Low_Percent", ...
    "Repeatability95_High_Percent", ...
    "Repeatability95_Low_dB", "Repeatability95_High_dB"]);
writetable(keyMetricComparison, fullfile(outputFolder, ...
    "Current_1p2_vs_Nominal_Key_Metrics.csv"));

frequencyHz = current.octaveFrequencyHz;
currentAsdVPerSqrtHz = current.ensembleOctaveAsdVPerSqrtHz;
nominalAsdVPerSqrtHz = nominal.ensembleOctaveAsdVPerSqrtHz;
currentVsNominalCurveDb = 20*log10( ...
    currentAsdVPerSqrtHz./nominalAsdVPerSqrtHz);
curveTable = table(frequencyHz, currentAsdVPerSqrtHz, ...
    nominalAsdVPerSqrtHz, currentVsNominalCurveDb, ...
    VariableNames=["Frequency_Hz", ...
    "Current1p2_ASD_V_per_rtHz", ...
    "NominalCurrent_ASD_V_per_rtHz", ...
    "Current1p2_vs_Nominal_dB"]);
writetable(curveTable, fullfile(outputFolder, ...
    "Current_1p2_vs_Nominal_1over12Octave.csv"));

comparisonFigure = figure(Name="1.2x current comparison", Color="w", ...
    Position=[100, 100, 1200, 850]);
layout = tiledlayout(comparisonFigure, 2, 1, ...
    TileSpacing="compact", Padding="compact");

topAxes = nexttile(layout);
set(topAxes, XScale="log", YScale="log");
loglog(topAxes, frequencyHz, nominalAsdVPerSqrtHz, ...
    LineWidth=1.8, Color=[0.15, 0.45, 0.75], ...
    DisplayName="Nominal current");
hold(topAxes, "on");
loglog(topAxes, frequencyHz, currentAsdVPerSqrtHz, ...
    LineWidth=1.8, Color=[0.85, 0.325, 0.098], ...
    DisplayName="1.2x current");
hold(topAxes, "off");
grid(topAxes, "on");
xlim(topAxes, [1, 1e3]);
ylabel(topAxes, "ASD (V/\surdHz)");
title(topAxes, "20-run 1/12-octave PSD averages - " + methodLabel);
legend(topAxes, Location="best", Interpreter="none");

bottomAxes = nexttile(layout);
semilogx(bottomAxes, frequencyHz, currentVsNominalCurveDb, ...
    Color=[0.3, 0.3, 0.3], LineWidth=1.5);
hold(bottomAxes, "on");
yline(bottomAxes, 0, "k--", HandleVisibility="off");
hold(bottomAxes, "off");
grid(bottomAxes, "on");
xlim(bottomAxes, [1, 1e3]);
xlabel(bottomAxes, "Frequency (Hz)");
ylabel(bottomAxes, "1.2x / nominal (dB)");
title(bottomAxes, "Negative values mean lower noise at 1.2x current");

title(layout, "woShield current comparison using identical processing");
savefig(comparisonFigure, fullfile(outputFolder, ...
    "Current_1p2_vs_Nominal.fig"));
exportgraphics(comparisonFigure, fullfile(outputFolder, ...
    "Current_1p2_vs_Nominal.png"), Resolution=240);

fprintf("1.2x-current comparison saved under %s\n", outputFolder);
disp(keyMetricComparison);

function assertMatchingAnalysisSettings(currentSettings, ...
        nominalSettings, expectedProfile)
fieldsToMatch = ["segmentationMode", "segmentDurationSeconds", ...
    "segmentOverlapFraction", "windowName"];
for fieldName = fieldsToMatch
    field = char(fieldName);
    assert(isfield(currentSettings, field) && ...
        isfield(nominalSettings, field), ...
        "Missing analysis setting '%s'.", field);
    assert(isequal(currentSettings.(field), nominalSettings.(field)), ...
        "Analysis setting '%s' does not match.", field);
end
fftFieldsToMatch = ["fftLength", "segmentCount", ...
    "overlapSamples", "binSpacingHz", "enbwHz"];
for fieldName = fftFieldsToMatch
    field = char(fieldName);
    assert(isequal(currentSettings.fftInfo.(field), ...
        nominalSettings.fftInfo.(field)), ...
        "FFT setting '%s' does not match.", field);
end
if isfield(currentSettings, "analysisProfile") && ...
        isfield(nominalSettings, "analysisProfile")
    assert(strcmpi(currentSettings.analysisProfile, expectedProfile) && ...
        strcmpi(nominalSettings.analysisProfile, expectedProfile), ...
        "Saved result profile does not match '%s'.", expectedProfile);
elseif ~strcmpi(expectedProfile, "whole_record_22s")
    error("Saved Welch results lack analysis-profile metadata.");
end
end

function value = centeredFractionalOctaveAsd( ...
        frequencyHz, psd, centerHz, bandsPerOctave)
lowHz = centerHz*2^(-1/(2*bandsPerOctave));
highHz = centerHz*2^(1/(2*bandsPerOctave));
value = bandRmsAsd(frequencyHz, psd, lowHz, highHz);
end

function value = bandRmsAsd(frequencyHz, psd, lowHz, highHz)
[overlapHz, use] = binOverlap(frequencyHz, psd, lowHz, highHz);
averagePsd = sum(psd(use).*overlapHz(use))/sum(overlapHz(use));
value = sqrt(averagePsd);
end

function value = integrateNoise(frequencyHz, psd, lowHz, highHz)
[overlapHz, use] = binOverlap(frequencyHz, psd, lowHz, highHz);
value = sqrt(sum(psd(use).*overlapHz(use)));
end

function [overlapHz, use] = binOverlap( ...
        frequencyHz, psd, lowHz, highHz)
frequencyStepHz = median(diff(frequencyHz));
binLowHz = frequencyHz-frequencyStepHz/2;
binHighHz = frequencyHz+frequencyStepHz/2;
overlapHz = max(0, min(binHighHz, highHz)-max(binLowHz, lowHz));
use = overlapHz > 0 & isfinite(psd) & psd >= 0;
assert(any(use), "No FFT bins are available from %.9g to %.9g Hz.", ...
    lowHz, highHz);
end

function value = peakAsdInBand(frequencyHz, asd, lowHz, highHz)
use = frequencyHz >= lowHz & frequencyHz <= highHz;
assert(any(use), "No FFT bins are available from %.9g to %.9g Hz.", ...
    lowHz, highHz);
value = max(asd(use));
end

function values = calculateAmplitudeMetrics(frequencyHz, psd)
values = zeros(12, 1);
values(1) = centeredFractionalOctaveAsd(frequencyHz, psd, 1, 12);
values(2) = centeredFractionalOctaveAsd(frequencyHz, psd, 10, 12);
values(3) = centeredFractionalOctaveAsd(frequencyHz, psd, 1e3, 12);
values(4) = bandRmsAsd(frequencyHz, psd, 1, 10);
values(5) = bandRmsAsd(frequencyHz, psd, 10, 100);
values(6) = bandRmsAsd(frequencyHz, psd, 100, 1e3);
values(7) = integrateNoise(frequencyHz, psd, 1, 1e3);
values(8) = integrateNoise(frequencyHz, psd, 1, 25e3);
values(9) = peakAsdInBand(frequencyHz, sqrt(psd), 49, 51);
values(10) = integrateNoise(frequencyHz, psd, 49.5, 50.5);
values(11) = peakAsdInBand(frequencyHz, sqrt(psd), 149, 151);
values(12) = integrateNoise(frequencyHz, psd, 149.5, 150.5);
end
